### ISSUE TITLE
Public instance has non-existent mail from

### ISSUE THREAD

**Issue by szepeviktor** [sergeychernyshev/showslow#107]
`apache@ip-10-0-0-221.ec2.internal`

Please set something else.
It may block email reception.

**Comment by sergeychernyshev** [comment]
I added Amazon SES support and enabled it for mailing for public instance.

@szepeviktor could you please test and let me know if it worked?

**Comment by szepeviktor** [comment]
> From: Sergey Chernyshev <sergey@showslow.com>

Thank you.
