### ISSUE TITLE
Showslow is throwing error when accessing WPT result on Private instance- Please help

### ISSUE THREAD

**Issue by jyoprakash** [sergeychernyshev/showslow#109]
500 ShowSlow Error

Something went wrong. If it persists, please report it to issue tracker.

PageTest didn't accept the request: 404

<< go back to Show Slow

**Comment by sergeychernyshev** [comment]
Anything in error log?

**Comment by jyoprakash** [comment]
No log. Does showslow provides any log. I can see the urls in showslow and data in db but when i click on them lead me to the mentioned error

Sent from my iPhone

On Jun 2, 2015, at 12:59 AM, Sergey Chernyshev <notifications@github.com<mailto:notifications@github.com>> wrote:


Anything in error log?

**Comment by sergeychernyshev** [comment]
Sorry, I misinterpreted your request, thought it's a beacon that send the report.

It seems that your WPT instance is not where you expect it to be (returns 404), can you check if you're pointing at the correct WPT URL?

**Comment by jyoprakash** [comment]
I reconfigured the showslow:
I see that data is logged in database, but when I go to showslow the url constructed is as below and when I click I get “The requested URL /var/www/showslow/details/index.php was not found on this server.”

http://eespeedy.tools.us.gspt.net/showslow/details/1/http://www.google.com/<http://eespeedy.tools.us.gspt.net/showslow/details/1/http:/www.google.com/>


But when I click the following url I can access the complete data.
http://eespeedy.tools.us.gspt.net/showslow//details/?urlid=1&url=http://google.com/#webpagetest<http://eespeedy.tools.us.gspt.net/showslow/details/?urlid=1&url=http://google.com/#webpagetest>

Am I missing anything?

**Comment by jyoprakash** [comment]
Urlid in the constructed url and “Measurements over time” graph is missing

From: Prakash, Jyoti
Sent: Tuesday, June 02, 2015 11:09 PM
To: 'sergeychernyshev/showslow'; sergeychernyshev/showslow
Subject: RE: [showslow] Showslow is throwing error when accessing WPT result on Private instance- Please help (#109)

I reconfigured the showslow:
I see that data is logged in database, but when I go to showslow the url constructed is as below and when I click I get “The requested URL /var/www/showslow/details/index.php was not found on this server.”

http://eespeedy.tools.us.gspt.net/showslow/details/1/http://www.google.com/<http://eespeedy.tools.us.gspt.net/showslow/details/1/http:/www.google.com/>


But when I click the following url I can access the complete data.
http://eespeedy.tools.us.gspt.net/showslow//details/?urlid=1&url=http://google.com/#webpagetest<http://eespeedy.tools.us.gspt.net/showslow/details/?urlid=1&url=http://google.com/#webpagetest>

Am I missing anything?

**Comment by jyoprakash** [comment]
I can see the data in showslow DB , but when I click on See in ShowSlow in WPT then I get below error. Is it anything to do with DB?
Not Found
The requested URL /var/www/showslow/details/index.php was not found on this server.
________________________________
Apache/2.2.15 (CentOS) Server at eespeedy.tools.us.gspt.net Port 80


From: Prakash, Jyoti
Sent: Wednesday, June 03, 2015 1:21 PM
To: 'sergeychernyshev/showslow'; 'sergeychernyshev/showslow'
Subject: RE: [showslow] Showslow is throwing error when accessing WPT result on Private instance- Please help (#109)

Urlid in the constructed url and “Measurements over time” graph is missing

From: Prakash, Jyoti
Sent: Tuesday, June 02, 2015 11:09 PM
To: 'sergeychernyshev/showslow'; sergeychernyshev/showslow
Subject: RE: [showslow] Showslow is throwing error when accessing WPT result on Private instance- Please help (#109)

I reconfigured the showslow:
I see that data is logged in database, but when I go to showslow the url constructed is as below and when I click I get “The requested URL /var/www/showslow/details/index.php was not found on this server.”

http://eespeedy.tools.us.gspt.net/showslow/details/1/http://www.google.com/<http://eespeedy.tools.us.gspt.net/showslow/details/1/http:/www.google.com/>


But when I click the following url I can access the complete data.
http://eespeedy.tools.us.gspt.net/showslow//details/?urlid=1&url=http://google.com/#webpagetest<http://eespeedy.tools.us.gspt.net/showslow/details/?urlid=1&url=http://google.com/#webpagetest>

Am I missing anything?

**Comment by sergeychernyshev** [comment]
Looks like something is wrong with your URL mappings. What is your document
root?

**Comment by jyoprakash** [comment]
/var/www/webpagetest

**Comment by sergeychernyshev** [comment]
How's /var/www/webpagetest and /var/www/showslow relate to each other? is it the same virtual host?
