### ISSUE TITLE
Website is broken

### ISSUE THREAD

**Issue by danielhq** [sergeychernyshev/showslow#111]
www.showslow.org doesn't work anymore, as well as the download link from showslow.com

**Comment by sergeychernyshev** [comment]
I'm working on it.

**Comment by leslyarun** [comment]
download and documentation page is not available anymore. Kindly request you to fix it @sergeychernyshev

**Comment by sergeychernyshev** [comment]
Web site is up, will most likely migrate all the docs to the repo
