### ISSUE TITLE
[PageSpeed] Error 500 No score returned

### ISSUE THREAD

**Issue by Emil89EC** [sergeychernyshev/showslow#112]
When I'm trying to run a PageSpeed test I keep getting a *No score returned* error.
I see that PageSpeed results are being displayed on ShowSlow.com, any ideas what I have to modify in the *index.php* from *beacon/pagespeed* to at least get some basic results?

**Comment by sergeychernyshev** [comment]
I'm afraid, you'll need to use the version of PageSpeed that had metrics
that we collect, they stopped support for rankings a couple years ago,
unfortunately.

On Monday, September 14, 2015, Emil89EC <notifications@github.com> wrote:

> When I'm trying to run a PageSpeed test I keep getting a *No score
> returned* error.
> I see that PageSpeed results are being displayed on ShowSlow.com, any
> ideas what I have to modify in the *index.php* from *beacon/pagespeed* to
> at least get some basic results?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sergeychernyshev/showslow/issues/112>.
>


-- 

Best,

         Sergey


--
Sergey Chernyshev
http://www.sergeychernyshev.com/
http://www.meetup.com/Web-Performance-NY/
http://www.showslow.com/

**Comment by Emil89EC** [comment]
Thanks Sergey for the response. 
As I'm new to PHP and all that is ShowSlow, can you help me how I can do that? The changes must be made only for that beacon index.php? Sorry for pestering you with this, but I want to be able to use also the PageSpeed metrics together with YSlow (which seems to work fine), it doesn't matter If it's an older version of PageSpeed.
Thanks!

**Comment by sergeychernyshev** [comment]
You don't have to change any code in ShowSlow if you use older version of
PageSpeed - just run that version and it'll send the appropriate beacons to
ShowSlow.

**Comment by Emil89EC** [comment]
I left all the changes as is, and I'm getting the following error :( 

**500 BeaconError**

*You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') VALUES (inet_aton('86.122.168.47'), 'Mozilla/5.0 (Windows NT 10.0; WOW64) A' at line 5*

**Comment by Emil89EC** [comment]
I managed to get the PageSpeed Firefox extension (1.12.9.2) to work with an older version of FF (24) set the path for *extensions.PageSpeed.beacon.minimal.url* and made sure that *extensions.PageSpeed.beacon.minimal.enabled* is set to true, but no results appear.
I saw some issue reported on the Google Groups with PageSpeed extension not sending data but I didn't find any fix for this. Any ideas? Can I get ShowSlow working with PageSpeed like this?
Thanks!

**Comment by Emil89EC** [comment]
Managed to make it work with FF16 + FB 1.10.5 + PageSpeed 1.12.9.2.

**Comment by sergeychernyshev** [comment]
Glad it worked in the end. It's sad that Google team discontinued the
ranked beacons.


On Tuesday, September 15, 2015, Emil Cordun <notifications@github.com>
wrote:

> Managed to make it work with FF16 + FB 1.10.5 + PageSpeed 1.12.9.2.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sergeychernyshev/showslow/issues/112#issuecomment-140347873>
> .
>


-- 

Best,

         Sergey


--
Sergey Chernyshev
http://www.sergeychernyshev.com/
http://www.meetup.com/Web-Performance-NY/
http://www.showslow.com/
