### ISSUE TITLE
How can I add "Add URL" on my homepage

### ISSUE THREAD

**Issue by raiashish1** [sergeychernyshev/showslow#113]
Hi,

I am new to showslow and setting up showslow on my server however I am not seeing the "Add URL" like its shown on http://www.showslow.com/

Any help is much appreciated.

Thanks,
Ashish

**Comment by sergeychernyshev** [comment]
Check out advanced configuration: 
https://github.com/sergeychernyshev/showslow/wiki/Advanced-configuration-options#allowing-users-to-enter-their-urls-for-monitoring

**Comment by raiashish1** [comment]
Thank you.
