### ISSUE TITLE
/showslow/pagetest.php 展示PageTest returned failure status code: 400 (Invalid API Key)

### ISSUE THREAD

**Issue by fengshuai198904** [sergeychernyshev/showslow#123]
/showslow/pagetest.php
500 ShowSlow Error

Something went wrong. If it persists, please report it to issue tracker.

PageTest returned failure status code: 400 (Invalid API Key)

 备注：
[LINK REPLACED] 打不开，重定向到其他网页

**Comment by sergeychernyshev** [comment]
Link was broken and points at a spam (or even malware) site.

Error you're getting suggests that you are using an invalid API key for WebPageTest.

**Comment by fengshuai198904** [comment]
Where can I apply for the available webpagetest key ?please help @sergeychernyshev

**Comment by sergeychernyshev** [comment]
Your best chance is here, I believe:
https://www.webpagetest.org/getkey.php

**Comment by fengshuai198904** [comment]
thank you very much @sergeychernyshev
