### ISSUE TITLE
"showslow/details/?urlid=1&url=https://www.baidu.com/ ",  don,t show yslow result

### ISSUE THREAD

**Issue by fengshuai198904** [sergeychernyshev/showslow#124]
$ /usr/bin/phantomjs  /usr/local/phantomjs/examples/yslow.js  -i grade -b  
FAIL to load undefined

{"w":140335,"o":91,"u":"https%3A%2F%2Fwww.baidu.com%2F","r":14,"i":"ydefault","lt":347,"g":{"ynumreq":{"score":96,"message":"This page has 4 external Javascript scripts.  Try combining them into one.","components":[]},"ycdn":{"score":0,"message":"There are 11 static components that are not on CDN. <p>You can specify CDN hostnames in your preferences. See <a href=\"https://github.com/marcelduran/yslow/wiki/FAQ#wiki-faq_cdn\">YSlow FAQ</a> for details.</p>","components":["ss1.bdstatic.com%3A%209%20components%2C%20400.5K%20(40.3K%20GZip)","www.baidu.com%3A%202%20components%2C%208.5K"]},"yemptysrc":{"score":100,"message":"","components":[]},"yexpires":{"score":78,"message":"There are 2 static components without a far-future expiration date.","components":["https%3A%2F%2Fwww.baidu.com%2Ffavicon.ico","https%3A%2F%2Fwww.baidu.com%2Fimg%2Fbaidu.svg"]},"ycompress":{"score":100,"message":"","components":[]},"ycsstop":{"score":100,"message":"","components":[]},"yjsbottom":{"score":100,"message":"","components":[]},"yexpressions":{"score":100,"message":"","components":[]},"yexternal":{"message":"Only consider this if your property is a common user home page.","components":["There%20is%20a%20total%20of%204%20inline%20css","There%20is%20a%20total%20of%2012%20inline%20scripts"]},"ydns":{"score":100,"message":"","components":["www.baidu.com%3A%205%20components%2C%20122.4K%20(71.9K%20GZip)","ss1.bdstatic.com%3A%209%20components%2C%20400.5K%20(40.3K%20GZip)"]},"yminify":{"score":70,"message":"There are 3 components that can be minified","components":["inline%20%26lt%3Bscript%26gt%3B%20tag%20%235","inline%20%26lt%3Bscript%26gt%3B%20tag%20%236","inline%20%26lt%3Bscript%26gt%3B%20tag%20%238"]},"yredirects":{"score":100,"message":"","components":[]},"ydupes":{"score":100,"message":"","components":[]},"yetags":{"score":100,"message":"","components":[]},"yxhr":{"score":100,"message":"","components":[]},"yxhrmethod":{"score":100,"message":"","components":[]},"ymindom":{"score":100,"message":"","components":[]},"yno404":{"score":100,"message":"","components":[]},"ymincookie":{"score":100,"message":"","components":[]},"ycookiefree":{"score":100,"message":"","components":[]},"ynofilter":{"score":100,"message":"","components":[]},"yimgnoscale":{"score":100,"message":"","components":[]},"yfavicon":{"score":95,"message":"Favicon is not cacheable","components":[]}}}

why?
is  "FAIL to load undefined"  casued ,showslow don,t show yslow result.
please help @sergeychernyshev

**Comment by sergeychernyshev** [comment]
It is most likely an issue inside `yslow.js`, it did not work for me at all with latest `phantomjs`.

Seems like [Sitespeed.io](https://www.sitespeed.io/) is replacing ShowSlow and [Coach](https://www.sitespeed.io/documentation/coach/) is replacing YSlow, you might be better off with those tools.

**Comment by fengshuai198904** [comment]
thank you ! @sergeychernyshev
